export const API_ENDPOINTS = {
  me: "/me",
  adminMe: "/admin/me",
  adminTenants: "/admin/tenants",
  adminTenant: (id: string) => `/admin/tenants/${id}`,
  repos: "/repos",
  repo: (id: string) => `/repos/${id}`,
  employees: "/employees",
  employee: (id: string) => `/employees/${id}`,
  quizTemplates: "/quiz-templates",
  quizTemplate: (id: string) => `/quiz-templates/${id}`,
  quizAttempts: "/quiz-attempts",
  chat: "/chat",
  experts: "/experts",
  dashboardBusFactor: (repoId: string) => `/dashboard/bus-factor?repoId=${repoId}`,
  dashboardQuizAnalytics: (repoId: string) => `/dashboard/quiz-analytics?repoId=${repoId}`,
} as const;
