"""add organization table and tenant scoping

Revision ID: 0d9d425d9e66
Revises: dcc57c67553f
Create Date: 2026-07-16 18:24:42.111578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d9d425d9e66"
down_revision: Union[str, Sequence[str], None] = "dcc57c67553f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "code_chunk",
        "repo_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "code_chunk", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "commit_record",
        "repo_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "commit_record",
        "author_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "commit_record", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "contributor",
        "repo_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "contributor", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "employee", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.create_index(op.f("ix_employee_org_id"), "employee", ["org_id"], unique=False)
    op.create_foreign_key(None, "employee", "organization", ["org_id"], ["id"])
    op.alter_column(
        "expertise_availability",
        "contributor_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "expertise_availability",
        "id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "file_expertise",
        "repo_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "file_expertise",
        "contributor_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "file_expertise", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "institutional_memory_note",
        "contributor_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "institutional_memory_note",
        "id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "policy_doc", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.create_index(op.f("ix_policy_doc_org_id"), "policy_doc", ["org_id"], unique=False)
    op.create_foreign_key(None, "policy_doc", "organization", ["org_id"], ["id"])
    op.alter_column(
        "quiz_attempt",
        "employee_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "quiz_template_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "quiz_question",
        "quiz_template_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.alter_column(
        "quiz_template", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.add_column("repo", sa.Column("org_id", sa.String(length=64), nullable=False))
    op.alter_column(
        "repo", "id", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=64), existing_nullable=False
    )
    op.create_index(op.f("ix_repo_org_id"), "repo", ["org_id"], unique=False)
    op.create_foreign_key(None, "repo", "organization", ["org_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repo", type_="foreignkey")
    op.drop_index(op.f("ix_repo_org_id"), table_name="repo")
    op.alter_column(
        "repo", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.drop_column("repo", "org_id")
    op.alter_column(
        "quiz_template", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "quiz_question", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "quiz_question",
        "quiz_template_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "quiz_attempt",
        "quiz_template_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "employee_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(None, "policy_doc", type_="foreignkey")
    op.drop_index(op.f("ix_policy_doc_org_id"), table_name="policy_doc")
    op.alter_column(
        "policy_doc", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "institutional_memory_note",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "institutional_memory_note",
        "contributor_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "file_expertise", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "file_expertise",
        "contributor_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "file_expertise",
        "repo_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "expertise_availability",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "expertise_availability",
        "contributor_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_index(op.f("ix_employee_org_id"), table_name="employee")
    op.alter_column(
        "employee", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "contributor", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "contributor",
        "repo_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "commit_record", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "commit_record",
        "author_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "commit_record",
        "repo_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "code_chunk", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=20), existing_nullable=False
    )
    op.alter_column(
        "code_chunk",
        "repo_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_table("organization")
    # ### end Alembic commands ###
