"""Add project knowledge-base docs: is_knowledge_base + project_doc_type tables

Revision ID: 1bd454bb2a82
Revises: a42049ac344b
Create Date: 2026-07-18 19:12:31.066574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bd454bb2a82"
down_revision: Union[str, Sequence[str], None] = "a42049ac344b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_doc_type",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_doc_type_project_name"),
    )
    op.create_index(op.f("ix_project_doc_type_org_id"), "project_doc_type", ["org_id"], unique=False)
    op.create_index(op.f("ix_project_doc_type_project_id"), "project_doc_type", ["project_id"], unique=False)
    op.create_table(
        "project_document_type",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("doc_type_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["doc_type_id"], ["project_doc_type.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["doc_pack_document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "doc_type_id", name="uq_project_document_type_doc_type"),
    )
    op.create_index(
        op.f("ix_project_document_type_doc_type_id"), "project_document_type", ["doc_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_document_type_document_id"), "project_document_type", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_project_document_type_org_id"), "project_document_type", ["org_id"], unique=False)
    # NOTE: Alembic's pgvector HNSW index "drops" are false-positives (it can't introspect the
    # vector opclass) — removed so we don't drop the real embedding indexes.
    op.add_column("doc_pack", sa.Column("is_knowledge_base", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("doc_pack", "is_knowledge_base")
    op.drop_index(op.f("ix_project_document_type_org_id"), table_name="project_document_type")
    op.drop_index(op.f("ix_project_document_type_document_id"), table_name="project_document_type")
    op.drop_index(op.f("ix_project_document_type_doc_type_id"), table_name="project_document_type")
    op.drop_table("project_document_type")
    op.drop_index(op.f("ix_project_doc_type_project_id"), table_name="project_doc_type")
    op.drop_index(op.f("ix_project_doc_type_org_id"), table_name="project_doc_type")
    op.drop_table("project_doc_type")
    # ### end Alembic commands ###
