"""add track audience and auto assign

Revision ID: 5a085e65cf2b
Revises: d2e3f4a5b6c7
Create Date: 2026-07-17 22:28:04.193922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a085e65cf2b"
down_revision: Union[str, Sequence[str], None] = "d2e3f4a5b6c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "doc_pack_audience_domain",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("doc_pack_id", sa.String(length=64), nullable=False),
        sa.Column("org_domain_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["doc_pack_id"], ["doc_pack.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_domain_id"], ["org_domain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_pack_id", "org_domain_id", name="uq_pack_audience_pack_domain"),
    )
    op.create_index(
        op.f("ix_doc_pack_audience_domain_doc_pack_id"), "doc_pack_audience_domain", ["doc_pack_id"], unique=False
    )
    op.create_index(
        op.f("ix_doc_pack_audience_domain_org_domain_id"), "doc_pack_audience_domain", ["org_domain_id"], unique=False
    )
    op.create_index(op.f("ix_doc_pack_audience_domain_org_id"), "doc_pack_audience_domain", ["org_id"], unique=False)
    # NOTE: the autogenerated drop of 'ix_doc_chunk_embedding_hnsw' was removed — alembic can't read the
    # pgvector HNSW index and reports it as removed on every autogenerate. Leave the index in place.
    op.add_column("doc_pack", sa.Column("assign_to_all", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("pack_assignment", sa.Column("auto_assigned", sa.Boolean(), server_default="false", nullable=False))
    # New manual-only question type; ADD VALUE is idempotent and safe to run outside the "use it" tx.
    op.execute("ALTER TYPE question_format ADD VALUE IF NOT EXISTS 'multi_select'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres can't drop an enum value in place; leaving 'multi_select' on question_format is harmless.
    op.drop_column("pack_assignment", "auto_assigned")
    op.drop_column("doc_pack", "assign_to_all")
    op.drop_index(op.f("ix_doc_pack_audience_domain_org_id"), table_name="doc_pack_audience_domain")
    op.drop_index(op.f("ix_doc_pack_audience_domain_org_domain_id"), table_name="doc_pack_audience_domain")
    op.drop_index(op.f("ix_doc_pack_audience_domain_doc_pack_id"), table_name="doc_pack_audience_domain")
    op.drop_table("doc_pack_audience_domain")
