"""Add doc_pack.assign_scope for project module targeting

Revision ID: 81a4fe985f7a
Revises: c1d2e3f4a5b6
Create Date: 2026-07-18 18:01:14.923681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81a4fe985f7a"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: the pgvector HNSW index drops Alembic autogenerated are false-positives (it can't
    # introspect the vector opclass) — removed so we don't drop the real embedding indexes.
    assign_scope = sa.Enum("all_members", "manual", name="doc_pack_assign_scope")
    assign_scope.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "doc_pack",
        sa.Column("assign_scope", assign_scope, server_default="all_members", nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("doc_pack", "assign_scope")
    sa.Enum(name="doc_pack_assign_scope").drop(op.get_bind(), checkfirst=True)
