"""add team leads, project repos/context, modules and function types

Revision ID: 9ce7a0813a6e
Revises: b7f3c2a19d84
Create Date: 2026-07-18 02:07:57.590171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ce7a0813a6e'
down_revision: Union[str, Sequence[str], None] = 'b7f3c2a19d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_function_type',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_function_type_project_name')
    )
    op.create_index(op.f('ix_project_function_type_org_id'), 'project_function_type', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_function_type_project_id'), 'project_function_type', ['project_id'], unique=False)
    op.create_table('project_module',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resource_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='project_module_status'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_module_org_id'), 'project_module', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_module_project_id'), 'project_module', ['project_id'], unique=False)
    op.create_table('project_repo',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('repo_id', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'repo_id', name='uq_project_repo_project_repo')
    )
    op.create_index(op.f('ix_project_repo_org_id'), 'project_repo', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_repo_project_id'), 'project_repo', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_repo_repo_id'), 'project_repo', ['repo_id'], unique=False)
    op.create_table('project_module_assignment',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=True),
    sa.Column('auto_assigned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', name='project_module_assignment_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['project_module.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'employee_id', name='uq_project_module_assignment_module_employee')
    )
    op.create_index(op.f('ix_project_module_assignment_employee_id'), 'project_module_assignment', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_module_assignment_module_id'), 'project_module_assignment', ['module_id'], unique=False)
    op.create_index(op.f('ix_project_module_assignment_org_id'), 'project_module_assignment', ['org_id'], unique=False)
    op.create_table('project_module_type',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('function_type_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['function_type_id'], ['project_function_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['project_module.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'function_type_id', name='uq_project_module_type_module_function')
    )
    op.create_index(op.f('ix_project_module_type_function_type_id'), 'project_module_type', ['function_type_id'], unique=False)
    op.create_index(op.f('ix_project_module_type_module_id'), 'project_module_type', ['module_id'], unique=False)
    op.create_index(op.f('ix_project_module_type_org_id'), 'project_module_type', ['org_id'], unique=False)
    # Backfill the new repo-list table from each project's legacy single `repo_id` (as its primary repo).
    op.execute(
        "INSERT INTO project_repo (id, org_id, project_id, repo_id, is_primary, created_at, updated_at) "
        "SELECT 'prepo_' || replace(gen_random_uuid()::text, '-', ''), org_id, id, repo_id, true, now(), now() "
        "FROM project WHERE repo_id IS NOT NULL"
    )
    op.add_column('project', sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('project', sa.Column('resource_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('project', sa.Column('glossary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('project_member', sa.Column('is_lead', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('project_member', sa.Column('function_type_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_project_member_function_type_id'), 'project_member', ['function_type_id'], unique=False)
    op.create_foreign_key(None, 'project_member', 'project_function_type', ['function_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_member', type_='foreignkey')
    op.drop_index(op.f('ix_project_member_function_type_id'), table_name='project_member')
    op.drop_column('project_member', 'function_type_id')
    op.drop_column('project_member', 'is_lead')
    op.drop_column('project', 'glossary')
    op.drop_column('project', 'resource_links')
    op.drop_column('project', 'tech_stack')
    op.drop_index(op.f('ix_project_module_type_org_id'), table_name='project_module_type')
    op.drop_index(op.f('ix_project_module_type_module_id'), table_name='project_module_type')
    op.drop_index(op.f('ix_project_module_type_function_type_id'), table_name='project_module_type')
    op.drop_table('project_module_type')
    op.drop_index(op.f('ix_project_module_assignment_org_id'), table_name='project_module_assignment')
    op.drop_index(op.f('ix_project_module_assignment_module_id'), table_name='project_module_assignment')
    op.drop_index(op.f('ix_project_module_assignment_employee_id'), table_name='project_module_assignment')
    op.drop_table('project_module_assignment')
    op.drop_index(op.f('ix_project_repo_repo_id'), table_name='project_repo')
    op.drop_index(op.f('ix_project_repo_project_id'), table_name='project_repo')
    op.drop_index(op.f('ix_project_repo_org_id'), table_name='project_repo')
    op.drop_table('project_repo')
    op.drop_index(op.f('ix_project_module_project_id'), table_name='project_module')
    op.drop_index(op.f('ix_project_module_org_id'), table_name='project_module')
    op.drop_table('project_module')
    op.drop_index(op.f('ix_project_function_type_project_id'), table_name='project_function_type')
    op.drop_index(op.f('ix_project_function_type_org_id'), table_name='project_function_type')
    op.drop_table('project_function_type')
    # ### end Alembic commands ###
