"""Add project_repo_member for repo-member assignment

Revision ID: a42049ac344b
Revises: 81a4fe985f7a
Create Date: 2026-07-18 18:32:55.913206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a42049ac344b"
down_revision: Union[str, Sequence[str], None] = "81a4fe985f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_repo_member",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("project_repo_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("added_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(["project_repo_id"], ["project_repo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_repo_id", "employee_id", name="uq_project_repo_member_link_employee"),
    )
    op.create_index(op.f("ix_project_repo_member_employee_id"), "project_repo_member", ["employee_id"], unique=False)
    op.create_index(op.f("ix_project_repo_member_org_id"), "project_repo_member", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_project_repo_member_project_repo_id"), "project_repo_member", ["project_repo_id"], unique=False
    )
    # NOTE: Alembic's pgvector HNSW index "drops" are false-positives (it can't introspect the
    # vector opclass) — removed so we don't drop the real embedding indexes.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_project_repo_member_project_repo_id"), table_name="project_repo_member")
    op.drop_index(op.f("ix_project_repo_member_org_id"), table_name="project_repo_member")
    op.drop_index(op.f("ix_project_repo_member_employee_id"), table_name="project_repo_member")
    op.drop_table("project_repo_member")
    # ### end Alembic commands ###
