"""add track sequencing, due dates, pass_pct, notifications

Revision ID: eb463e90c5f2
Revises: 5a085e65cf2b
Create Date: 2026-07-17 23:21:07.881767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb463e90c5f2"
down_revision: Union[str, Sequence[str], None] = "5a085e65cf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column(
            "type", sa.Enum("assignment", "overdue", "outcome", "digest", name="notification_type"), nullable=False
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=1024), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_employee_id"), "notification", ["employee_id"], unique=False)
    op.create_index(op.f("ix_notification_org_id"), "notification", ["org_id"], unique=False)
    # NOTE: the autogenerated drop of 'ix_doc_chunk_embedding_hnsw' was removed — alembic can't read the
    # pgvector HNSW index and reports it as removed on every autogenerate. Leave the index in place.
    op.add_column("doc_pack", sa.Column("pass_pct", sa.Integer(), server_default="100", nullable=False))
    op.add_column("doc_pack", sa.Column("sequence_order", sa.Integer(), server_default="0", nullable=False))
    op.add_column("doc_pack", sa.Column("estimated_minutes", sa.Integer(), nullable=True))
    op.add_column("doc_pack", sa.Column("due_offset_days", sa.Integer(), nullable=True))
    op.add_column("pack_assignment", sa.Column("due_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pack_assignment", "due_at")
    op.drop_column("doc_pack", "due_offset_days")
    op.drop_column("doc_pack", "estimated_minutes")
    op.drop_column("doc_pack", "sequence_order")
    op.drop_column("doc_pack", "pass_pct")
    op.drop_index(op.f("ix_notification_org_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_employee_id"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
